[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.26"
rayon = "1.5.1"
ocl = "0.19"
quad = "0.1.2"

[toolchain]
channel = "nightly"
